v4.0 install improvements

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 
 INSTALLDIR="/usr/local"
+if [ ! -d $INSTALLDIR/bin ] || [ ! -d $INSTALLDIR/share ]; then
+  echo -e "\nCannot install in $INSTALLDIR, bin and share sub-directories do not exist"
+  exit 1
+fi
 # Check pre-reqs
 if [ -z $(which rsync) ]; then
   echo "rsync not found"
@@ -24,12 +28,13 @@ if [ -z $lua ]; then
   echo "Lua not found"
   exit 1
 fi
-lua check-prereqs.lua
+#export LUA_PATH="/usr/local/lib/lua/5.4/?.lua;;"
+#export LUA_CPATH="/usr/local/lib/lua/5.4/?.so;;"
+$lua check-prereqs.lua
 if [ $? -ne 0 ]; then
   echo "Pre-reqs not installed"
   exit 1
 fi
-[ ! -d $INSTALLDIR/bin ] && mkdir -p $INSTALLDIR/bin
 install -m 755 linux/multi-sync $INSTALLDIR/bin
 [ ! -d $INSTALLDIR/share/multi-sync ] && mkdir -p $INSTALLDIR/share/multi-sync
 install -m 644 multi-sync.lua $INSTALLDIR/share/multi-sync
