v4.0

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,6 +16,10 @@ else
   USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
 fi
 # Check pre-reqs
+if [ -z $(which rsync) ]; then
+  echo "rsync not found"
+  exit 1
+fi
 lua=$(which lua5.4)
 if [ ! -z $lua ]; then
   luav=5.4
