v4.0.1

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,35 +1,41 @@
 #!/usr/bin/env bash
 
+if [ $EUID -ne 0 ]; then
+  echo "This script must be run as root" >&2
+  set -e
+  exit 1
+fi
+
 INSTALLDIR="/usr/local"
 if [ ! -d $INSTALLDIR/bin ] || [ ! -d $INSTALLDIR/share ]; then
-  echo -e "\nCannot install in $INSTALLDIR, bin and share sub-directories do not exist"
+  echo -e "\n$INSTALLDIR/bin and/or $INSTALLDIR/share does not exist, cannot install"
   exit 1
 fi
 # Check pre-reqs
-if [ -z $(which rsync) ]; then
+if [ -z "$(which rsync)" ]; then
   echo "rsync not found"
   exit 1
 fi
 lua=$(which lua5.4)
-if [ ! -z $lua ]; then
+if [ -n "$lua" ]; then
   luav=5.4
 else
   lua=$(which lua5.3)
-  if [ ! -z $lua ]; then
+  if [ -n "$lua" ]; then
     luav=5.3
   else
     lua=$(which lua5.2)
-    if [ ! -z $lua ]; then
+    if [ -n "$lua" ]; then
       luav=5.2
     fi
   fi
 fi
-if [ -z $lua ]; then
+if [ -z "$lua" ]; then
   echo "Lua not found"
   exit 1
 fi
-#export LUA_PATH="/usr/local/lib/lua/5.4/?.lua;;"
-#export LUA_CPATH="/usr/local/lib/lua/5.4/?.so;;"
+#export LUA_PATH="/usr/local/lib/lua/$luav/?.lua;;"
+#export LUA_CPATH="/usr/local/lib/lua/$luav/?.so;;"
 $lua check-prereqs.lua
 if [ $? -ne 0 ]; then
   echo "Pre-reqs not installed"
